[BOJ]2805.py
틀리지 않은 것 같은데 시간초과 나네요..?
sum하는 부분 때문인 것 같은데 리뷰해주세요
=> [양수영] (BOJ - 2805) 나무 자르기 풀이

[BOJ]10828.py
파이썬으로 푸니 너무 간단했던 문제였습니다.
이 문제가 input으로 하면 시간초과나고
sys.stdin으로 하면 패스되는 문제였네요
한 번 해보세요!
=> [양수영] (BOJ - 10828) 스택 풀이

[BOJ]10845.py
=> [양수영] (BOJ - 10845) 큐 풀이

[BOJ]1991.py
=> [양수영] (BOJ - 1991) 트리 순회 풀이

[BOJ]2042.py
=> [양수영] (BOJ - 2042) 구간 합 구하기 풀이

.gitignore, 10845/main.cpp
Circular Queue 기반으로 풀어보았습니다.
- push가 worst case에 N번까지 일어날 수 있어서 사실 Circular Queue의 의미는 크게 없지만
정해진 크기 안에서 push와 pop이 일어나는 경우 매우 효율적인 자료형이기 떄문에 참고하셨으면 좋겠습니다.
=> [양태영] (BOJ - 10845) 큐 풀이

1991/main.py
=> [양태영] (BOJ - 1991) 트리 순회 풀이

.gitignore, 2042/main.py
이번 문제는 정말 어려웠군요.. 어쩐지 처음엔 너무 쉽더라.... 아껴서 풀걸...
=> [양태영] (BOJ - 2042) 구간 합 구하기 풀이

[BOJ]1717.py
=> [양수영] (BOJ - 1717) 집합의 표현 풀이

[BOJ]1922.py
괜히 힙으로 안풀겠다고 객기부리다 오래걸렸네요
힙 짱짱맨.......
=> [양수영] (BOJ - 1922) 네트워크 연결 풀이

1717/main.py
언어적 특성을 많이 타는 문제입니다.
또한 제한 조건 역시 매우 까다롭기 때문에, 알고리즘을 알고 있다고 해도 풀기 어려운 문제입니다.
특히 Union Find를 구현하는 방식이 여러가지인데, 초기화 시점과 같은 것들이 문제의 제한조건에 포함되어 있지 않기 때문에 이를 확인하려면 여러번 테스트를 돌려봐야만 확인이 가능한 문제였네요.
=> [양태영] (BOJ - 1717) 집합의 표현 풀이

2252/main.py
=> [양태영] (BOJ - 2252) 줄세우기 풀이

1922/main.py
Wiki: https://github.com/2022-2digit-study/2022-algorithm-study/wiki/%5BGiraffe%5D-Kruskal-Algorithm
=> [양태영] (BOJ - 1922) 네트워크 연결 풀이

[BOJ]2252.py
위상수학이 생각나는 즐거운 문제였습니다.
골드3치고 생각보다 쉬웠네요.
그런데 코드 보고 풀지는 않았지만 위상정렬 개념은 좀 정리하고싶은데 위키써도 되나요?
=> [양수영] (BOJ - 2252) 줄 세우기 풀이

프린터.py
=> [손명기](프로그래머스-스택/큐) 프린터 풀이

11266/main.py
Wiki: https://github.com/2022-2digit-study/2022-algorithm-study/wiki/%5BGiraffe%5D-Articulation-Point
=> [양태영] (BOJ - 11266) 단절점 풀이

전화번호목록.py
=> [손명기] (프로그래머스: 해시) 전화번호 목록 풀이

주식가격.py
=> [손명기] (프로그래머스:스택/큐) 주식가격 문제풀이

다리를지나는트럭.py
=> [손명기] (프로그래머스: 스택/큐) 다리를 지나는 트럭 문제 풀이

[BOJ]1753.py
다익스트라 2년만이네여... 반가웠읍니다... 안녕히가세요...
=> [양수영] (BOJ - 1753) 최단경로 풀이

2960/main.py
=> [양태영] (BOJ - 2960) 에라토스테네스의 체 풀이

1753/main.py
알고리즘 수업을 들었던 뒤 오랜 기간 안 풀었던 문제인데 반갑군요
=> [양태영] (BOJ - 1753) 최단경로 풀이

1735/main.py
=> [양태영] (BOJ - 1735) 분수 합 풀이

[BOJ]2960.py
=> [양수영] (BOJ - 2960) 에라토스테네스의 체 풀이

[BOJ]3955.py
예외처리 너무 신경 안써서 하루종일 걸렸네요 ㅠ
예외처리부분은 다른 분 풀이를 참고해서 위키써야하는데,
오늘 기린님 discussion 설명드리고 쓸게여!
=> [양수영] (BOJ - 3955) 캔디 분배 풀이

11657/main.py
벨만 포드라는 알고리즘은 익숙하진 않은데 개념은 확실히 쉽군요.
=> [양태영] (BOJ - 11657) 타임머신 풀이

11404/main.py
알고리즘 시험 때문에 버릇처럼 외웠던 코드인데.. 드디어 빛을 발하네요
=> [양태영] (BOJ - 11404) 플로이드 풀이
